/**
 * 영문 tag → 한글 라벨 매핑
 *
 * training_flow의 options/accepted_answers는 영문 slug로 저장되고
 * UI에서는 이 맵을 통해 한글로 표시
 *
 * 매핑이 없으면 slug를 그대로 표시 (→ 로 읽기 편하게 변환)
 */

const TAG_LABELS: Record<string, string> = {
  // ─── Goal types (reading.goal_type) ──────────────────────
  count: '개수 (count)',
  minimum_cost: '최소 비용',
  maximum_sum: '최대 합',
  maximum_value: '최대 값',
  minimum_value: '최소 값',
  indices: '인덱스 반환',
  boolean_existence: '존재 여부 (true/false)',
  all_combinations: '모든 조합',
  value: '값 계산',
  shortest_path: '최단 경로',
  longest_path: '최장 경로',
  string_output: '문자열 출력',
  sequence: '수열/순서',
  construction: '구성/만들기',

  // ─── Input types (reading.input_summary) ─────────────────
  interval_pairs: '구간 쌍 (시작, 끝)',
  sorted_data: '정렬된 데이터',
  graph_like_relation: '그래프 형태 관계',
  single_array: '1차원 배열',
  '1d_array': '1차원 배열',
  '2d_array': '2차원 배열',
  can_overlap: '겹침 가능',
  string_expression: '문자열 수식',
  only_plus_minus_operators: '+, - 연산자만',
  parentheses_can_be_added: '괄호 추가 가능',
  contains_negative_numbers: '음수 포함',
  contains_zero: '0 포함',
  can_pair_multiply: '쌍으로 묶어 곱하기 가능',
  merge_pairwise: '둘씩 병합',
  cost_depends_on_merge_order: '합치는 순서에 따라 비용 변동',
  coin_denominations: '동전 종류',
  coins_are_multiples_of_previous: '동전이 배수 관계',
  target_value_given: '목표 값 주어짐',
  sorted_ascending: '오름차순 정렬',
  tree_structure: '트리 구조',
  weighted_edges: '가중치 간선',
  unweighted_edges: '비가중치 간선',
  directed_graph: '방향 그래프',
  undirected_graph: '무방향 그래프',
  adjacency_list: '인접 리스트',
  matrix_input: '행렬 입력',
  pair_array: '쌍 배열',
  string_input: '문자열 입력',
  integer_sequence: '정수 수열',
  coordinate_pairs: '좌표 쌍',

  // ─── One-line summaries (reading.one_line_summary) ───────
  max_non_overlapping_intervals: '겹치지 않는 구간 최대 선택',
  activity_selection_problem: '활동 선택 문제',
  maximum_meetings_without_conflict: '충돌 없는 최대 회의 수',
  minimize_expression_by_adding_parentheses: '괄호 추가로 식 최소화',
  group_additions_after_minus_to_minimize: '마이너스 뒤 덧셈 묶어 최소화',
  maximize_sum_by_pairing_and_multiplying: '쌍 묶어 곱해서 합 최대화',
  optimal_number_bundling_for_max_sum: '최적 수 묶기로 최대 합',
  minimize_total_merge_cost: '총 병합 비용 최소화',
  optimal_merge_order_huffman: '최적 병합 순서 (허프만)',
  minimum_coins_for_target_with_multiples: '배수 동전으로 최소 개수',
  greedy_coin_change_with_divisibility: '배수 관계 그리디 동전',

  // ─── Primary patterns (pattern_analysis) ─────────────────
  brute_force: '완전 탐색 (Brute Force)',
  greedy_interval: '그리디 — 구간 선택',
  greedy_grouping: '그리디 — 그룹 묶기',
  greedy_classification: '그리디 — 분류 후 처리',
  greedy_min_heap: '그리디 — 최소 힙',
  greedy_largest_first: '그리디 — 큰 것부터',
  dp_interval: 'DP — 구간',
  dp: '동적 프로그래밍 (DP)',
  dp_backward: 'DP — 역방향',
  dp_forward: 'DP — 정방향',
  dp_coin_change: 'DP — 동전 교환',
  dp_knapsack: 'DP — 배낭',
  dp_lis: 'DP — 최장 증가 부분수열',
  dp_bitmask: 'DP — 비트마스크',
  dp_digit: 'DP — 자릿수',
  dp_tree: 'DP — 트리',
  dp_2d: 'DP — 2차원',
  two_pointers: '투 포인터',
  binary_search: '이분 탐색',
  parametric_search: '매개변수 탐색',
  dfs: '깊이 우선 탐색 (DFS)',
  bfs: '너비 우선 탐색 (BFS)',
  dfs_backtracking: 'DFS + 백트래킹',
  stack_based: '스택 기반',
  sorting_only: '정렬',
  divide_and_conquer: '분할 정복',
  union_find: '유니온 파인드',
  dijkstra: '다익스트라',
  bellman_ford: '벨만-포드',
  floyd_warshall: '플로이드-워셜',
  kruskal: '크루스칼 (MST)',
  topological_sort: '위상 정렬',
  segment_tree: '세그먼트 트리',
  trie: '트라이',
  math_formula: '수학 공식',

  // ─── Reason tags ─────────────────────────────────────────
  need_maximize_count: '개수 최대화 필요',
  locally_optimal_gives_global_optimal: '국소 최적 → 전역 최적',
  overlapping_subproblems: '겹치는 부분 문제',
  optimal_substructure: '최적 부분 구조',
  need_shortest_path: '최단 경로 필요',
  need_connected_components: '연결 요소 필요',
  need_ordering: '순서 필요',
  first_minus_makes_all_after_subtractable: '첫 마이너스 이후 모두 빼기 가능',
  grouping_plus_after_minus_is_always_optimal: '마이너스 뒤 덧셈 묶기가 항상 최적',
  need_dp_for_optimal_substructure: '최적 부분 구조에 DP 필요',
  need_stack_for_nested_structure: '중첩 구조에 스택 필요',
  classify_positive_negative_zero: '양수/음수/0 분류',
  locally_optimal_pairing: '국소 최적 쌍 매칭',
  smallest_first_minimizes_repeated_addition: '작은 것 먼저 합치면 반복 비용 최소',
  merged_result_reenters_candidates: '합친 결과가 후보에 재진입',
  coins_divisibility_guarantees_greedy: '동전 배수 관계가 그리디 보장',
  largest_coin_always_optimal: '큰 동전부터 항상 최적',
  need_dp_for_general_coins: '일반 동전은 DP 필요',
  need_optimal_substructure: '최적 부분 구조 필요',

  // ─── Secondary patterns ──────────────────────────────────
  sorting_preprocessing: '정렬 전처리',
  single_pass: '한 번 순회',
  counting: '카운팅',
  dp_optimization: 'DP 최적화',
  graph_traversal: '그래프 탐색',
  string_split: '문자열 분리',
  accumulation: '누적',
  priority_queue_usage: '우선순위 큐 사용',
  huffman_like: '허프만 코딩 유사',
  division_and_modulo: '나눗셈과 나머지',
  reverse_iteration: '역순 순회',
  prefix_sum: '누적합',
  sliding_window: '슬라이딩 윈도우',
  binary_search_optimization: '이분 탐색 최적화',
  memoization: '메모이제이션',
  backtracking: '백트래킹',

  // ─── Data structures ────────────────────────────────────
  array: '배열',
  set: '집합 (Set)',
  map: '맵 (Map / HashMap)',
  stack: '스택',
  queue: '큐',
  priority_queue: '우선순위 큐 (힙)',
  dp_array: 'DP 배열',
  dp_table: 'DP 테이블',
  linked_list: '연결 리스트',
  deque: '덱 (Deque)',
  tree: '트리',
  graph: '그래프',
  hash_set: '해시 집합',
  hash_map: '해시맵',
  disjoint_set: '서로소 집합',

  // ─── Approach tags (strategy_design) ─────────────────────
  sort_by_end_time: '끝나는 시간 기준 정렬',
  sort_by_start_time: '시작 시간 기준 정렬',
  sort_by_duration: '길이 기준 정렬',
  iterate_and_select: '순회하며 선택',
  track_last_end_time: '마지막 끝 시간 추적',
  dp_with_binary_search: 'DP + 이분 탐색',
  split_by_minus: '마이너스 기준 분리',
  sum_each_group: '각 그룹 합산',
  add_first_group_subtract_rest: '첫 그룹 더하고 나머지 빼기',
  try_all_parentheses: '모든 괄호 조합 시도',
  stack_based_evaluation: '스택 기반 계산',
  separate_positive_negative_zero: '양수/음수/0 분리',
  sort_positive_desc_negative_asc: '양수 내림차순, 음수 오름차순',
  pair_largest_positives: '큰 양수끼리 묶기',
  pair_smallest_negatives: '작은 음수끼리 묶기',
  one_should_not_be_multiplied: '1은 곱하지 않기',
  zero_cancels_leftover_negative: '0으로 남은 음수 상쇄',
  insert_all_to_min_heap: '전부 최소 힙에 삽입',
  extract_two_smallest: '가장 작은 두 개 추출',
  merge_and_reinsert: '합쳐서 다시 삽입',
  accumulate_cost: '비용 누적',
  sort_and_merge_sequentially: '정렬 후 순서대로 합치기',
  iterate_coins_largest_first: '큰 동전부터 순회',
  use_division_for_count: '나눗셈으로 개수 계산',
  update_remainder_with_modulo: '나머지로 갱신',
  dp_bottom_up: 'DP 바텀업',
  dp_top_down: 'DP 탑다운',
  try_all_combinations: '모든 조합 시도',

  // ─── Sorting rules ──────────────────────────────────────
  no_sorting_needed: '정렬 불필요',

  // ─── Edge cases ──────────────────────────────────────────
  same_end_time_sort_by_start: '끝 시간 같으면 시작 시간으로 정렬',
  start_equals_end_zero_length: '시작=끝 (길이 0 회의)',
  start_equals_prev_end_allowed: '시작=이전 끝 허용',
  integer_overflow_large_time: '정수 오버플로우 (큰 시간)',
  empty_input: '빈 입력',
  single_meeting: '회의 1개',
  all_meetings_overlap: '모든 회의 겹침',
  no_minus_in_expression: '식에 마이너스 없음',
  leading_zeros_in_numbers: '숫자 앞의 0',
  only_one_number: '숫자 1개',
  minus_at_start: '시작이 마이너스',
  all_numbers_zero: '모든 숫자 0',
  consecutive_operators: '연속 연산자',
  one_should_add_not_multiply: '1은 곱하지 말고 더하기',
  odd_negatives_use_zero: '홀수 음수 → 0으로 상쇄',
  no_zero_odd_negatives_just_add: '0 없고 음수 홀수 → 그냥 더하기',
  single_element_no_pair: '원소 1개 (짝 없음)',
  all_zeros: '모두 0',
  overflow_possible: '오버플로우 가능',
  all_ones: '모두 1',
  single_bundle_no_merge: '묶음 1개 (합칠 필요 없음)',
  merged_result_must_reenter_heap: '합친 결과를 힙에 재삽입',
  total_cost_overflow_use_long: '총 비용 오버플로우 → long 사용',
  all_same_size_bundles: '모든 묶음 크기 동일',
  two_bundles_only: '묶음 2개만',
  greedy_only_valid_with_multiples: '그리디는 배수 관계일 때만 유효',
  coin_larger_than_K_skip: '동전 > K면 건너뛰기',
  K_equals_zero: 'K = 0',
  single_coin_type: '동전 종류 1개',
  general_coins_need_dp: '일반 동전은 DP 필요',
  negative_cycle: '음수 사이클',
  disconnected_graph: '비연결 그래프',
  self_loop: '자기 루프',
  duplicate_edges: '중복 간선',
  single_node: '노드 1개',

  // ─── Complexity ──────────────────────────────────────────
  'O(1)': 'O(1) — 상수',
  'O(N)': 'O(N) — 선형',
  'O(NlogN)': 'O(N log N)',
  'O(N^2)': 'O(N²)',
  'O(N^3)': 'O(N³)',
  'O(2^N)': 'O(2ᴺ) — 지수',
  'O(N!)': 'O(N!) — 팩토리얼',
  'O(K)': 'O(K)',
  'O(N*K)': 'O(N×K)',
  'O(logN)': 'O(log N)',
  'O(VlogV)': 'O(V log V)',
  'O(V+E)': 'O(V + E)',
  'O(ElogV)': 'O(E log V)',

  // ─── Complexity reasons ──────────────────────────────────
  sorting_dominates: '정렬이 지배',
  single_pass_after_sort: '정렬 후 한 번 순회',
  only_track_last_end_variable: '마지막 끝 시간 변수만 추적',
  store_all_intervals: '모든 구간 저장',
  recursive_calls: '재귀 호출',
  single_pass_parsing: '한 번 파싱',
  split_creates_token_array: '분리 시 토큰 배열 생성',
  no_nested_loops: '중첩 루프 없음',
  store_all_elements: '모든 원소 저장',
  separate_lists_stored: '분류별 리스트 저장',
  constant_extra_space: '상수 추가 공간',
  heap_operations_logN_each: '힙 연산 각각 O(log N)',
  N_minus_1_merges: 'N-1번 병합',
  heap_stores_N_elements: '힙에 N개 저장',
  single_pass_through_coins: '동전 한 번 순회',
  only_count_and_remainder_variables: 'count와 remainder 변수만',
  no_extra_storage_needed: '추가 저장 불필요',
  dp_table_size_K: 'DP 테이블 크기 K',
};

// ─── Constraint keys ───────────────────────────────────────
const CONSTRAINT_LABELS: Record<string, string> = {
  input_size_hint: '입력 크기',

  // Greedy
  non_overlapping_required: '겹치지 않아야 함',
  simultaneous_end_start_allowed: '끝=시작 동시 허용',
  expression_length_max: '식 길이 제한',
  operators_plus_minus_only: '+, - 연산자만',
  can_bundle_pairs: '쌍으로 묶기 가능',
  negative_numbers_possible: '음수 가능',
  zero_included: '0 포함',
  must_merge_all: '전부 합쳐야 함',
  merge_cost_is_sum: '합치는 비용 = 합',
  coins_are_multiples: '동전이 배수 관계',
  unlimited_coins: '동전 무제한',

  // DP
  three_operations: '3가지 연산',
  divide_by_3_if_divisible: '3으로 나누어지면 ÷3',
  divide_by_2_if_divisible: '2로 나누어지면 ÷2',
  subtract_1: '-1',
  fibonacci_definition: '피보나치 정의',
  fib_0_is_0: 'F(0) = 0',
  fib_1_is_1: 'F(1) = 1',
  adjacent_digit_diff_is_1: '인접 자릿수 차이 = 1',
  no_leading_zero: '선행 0 불가',
  mod_1000000000: 'mod 10⁹',
  mod_10007: 'mod 10007',
  rectangle_height_is_2: '직사각형 높이 = 2',
  no_consecutive_ones: '연속 1 불가',
  binary_digits_only: '이진수만',
  binary_matrix: '0/1 행렬',
  answer_is_area_not_side: '정답은 넓이 (변 아님)',
  uppercase_only: '대문자만',
  lowercase_only: '소문자만',
  need_actual_lcs_string: '실제 LCS 문자열 필요',
  strictly_increasing: '순증가',
  need_actual_subsequence: '실제 부분수열 출력',
  each_day_has_duration_and_profit: '매일 기간+수익',
  consultation_must_finish_by_day_N: 'N일까지 상담 완료',
  can_remove_at_most_one: '최대 1개 제거 가능',
  must_select_at_least_one: '최소 1개 선택 필수',
  multiplication_is_associative: '곱셈 결합법칙',
  no_same_position_both_feet: '양발 같은 위치 불가',
  movement_costs_vary: '이동 비용 다양',
  visit_all_cities_exactly_once: '모든 도시 정확히 1번 방문',

  // Graph
  truth_propagation: '진실 전파',
  undirected_grouping: '무방향 그룹핑',
  negative_weights_possible: '음수 가중치 가능',
  undirected_graph: '무방향 그래프',
  positive_cycle_to_destination_check: '목적지까지 양의 사이클 확인',
  unreachable_case: '도달 불가 경우',
  reverse_direction: '역방향',
  multiple_answers_possible: '답이 여러 개 가능',
  all_pairs_shortest: '모든 쌍 최단경로',
  small_N: 'N이 작음',
  alphabet_to_number_conversion: '알파벳→숫자 변환',
  disconnected_returns_minus_1: '비연결 시 -1 반환',
  parallel_build_possible: '동시 건설 가능',
  predecessor_max_not_sum: '선행 최대값 (합 아님)',
  multiple_test_cases: '다중 테스트 케이스',
  may_be_disconnected: '비연결일 수 있음',
  path_compression_required: '경로 압축 필요',
  union_by_rank_required: '랭크 기반 합치기 필요',
  positive_weights_only: '양수 가중치만',
  priority_queue_needed: '우선순위 큐 필요',
  k_shortest_paths: 'K번째 최단 경로',
  revisit_allowed: '재방문 허용',
  positive_weights: '양수 가중치',
  single_source_single_dest: '단일 출발-도착',
  critical_path_and_edge_count: '임계 경로 + 간선 수',
  reverse_backtracking_needed: '역방향 추적 필요',
  connectivity_check: '연결성 확인',
  order_irrelevant: '순서 무관',
  state_space_small: '상태 공간 작음',
  six_transitions_per_state: '상태당 6가지 전이',
  any_valid_topological_order: '유효한 위상 순서 아무거나',
  no_cycle_guaranteed: '사이클 없음 보장',
  transitive_closure: '추이적 폐포',
  self_loop_via_cycle: '사이클 통한 자기 루프',
  multiple_edges_same_pair: '같은 쌍에 다중 간선',
  no_path_output_zero: '경로 없으면 0 출력',
  negative_weights: '음수 가중치',
  negative_cycle_detection: '음수 사이클 감지',
  bridge_straight_line_only: '다리는 직선만',
  bridge_length_at_least_2: '다리 길이 ≥ 2',
  unit_weight_edges: '가중치 1 간선',
  exact_distance_K: '정확히 거리 K',

  // Tree
  node_deletion: '노드 삭제',
  subtree_removal: '서브트리 제거',
  binary_tree: '이진 트리',
  root_is_A: '루트 = A',
  root_is_one: '루트 = 1',
  no_update_queries: '갱신 쿼리 없음',
  range_minimum_query: '구간 최솟값 쿼리',
  naive_lca_possible: '단순 LCA 가능',
  binary_lifting_required: '바이너리 리프팅 필요',
  point_update: '점 갱신',
  range_product_query: '구간 곱 쿼리',
  range_sum_query: '구간 합 쿼리',
  modular_arithmetic: '모듈러 연산',
  undirected_tree: '무방향 트리',
  membership_check: '포함 여부 확인',
  large_value_range: '값 범위 큼',

  // Number theory
  range_query: '범위 쿼리',
  sieve_required: '에라토스테네스 체 필요',
  gcd_lcm_required: 'GCD/LCM 필요',
  repunit_numbers: '레퍼닛 수',
  unsigned_64bit: '부호 없는 64비트',
  almost_prime_definition: '거의 소수 정의',
  large_range: '큰 범위',
  prime_and_palindrome: '소수 + 회문',
  sieve_range_larger_than_N: '체 범위 > N',
  euler_totient: '오일러 피 함수',
  large_n: 'N이 큼',
  squarefree_number: '제곱 인수 없는 수',
  range_sieve_required: '범위 체 필요',
  linear_diophantine: '일차 디오판토스 방정식',
  extended_gcd_required: '확장 유클리드 필요',
  tree_structure: '트리 구조',
  fraction_propagation: '분수 전파',

  // Data structures / Search / Sorting / etc.
  sorted_input: '정렬된 입력',
  coordinate_compression: '좌표 압축',
  merge_sort_based: '병합 정렬 기반',
  stable_sort_required: '안정 정렬 필요',
  custom_comparator: '사용자 정의 비교',

  // Combinatorics
  combination_formula: '조합 공식',
  modular_inverse: '모듈러 역원',
  pascal_triangle: '파스칼 삼각형',

  // Geometry
  circle_intersection: '원 교차',
  point_in_circle: '원 안의 점',
  line_segment_intersection: '선분 교차',
  cross_product: '외적',
};

/**
 * 영문 tag를 한글 라벨로 변환
 * 매핑이 없으면 underscore를 공백으로 바꿔서 반환
 */
export function getTagLabel(tag: string): string {
  if (TAG_LABELS[tag]) return TAG_LABELS[tag];
  // fallback: underscore → space, 첫 글자 대문자
  return tag.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}

/**
 * constraint key를 한글 라벨로 변환
 */
export function getConstraintLabel(key: string): string {
  if (CONSTRAINT_LABELS[key]) return CONSTRAINT_LABELS[key];
  return key.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}
