/**
 * 영문 tag → 한글 라벨 매핑
 *
 * training_flow의 options/accepted_answers는 영문 slug로 저장되고
 * UI에서는 이 맵을 통해 한글로 표시
 *
 * 매핑이 없으면 slug를 그대로 표시 (→ 로 읽기 편하게 변환)
 */

const TAG_LABELS: Record<string, string> = {
  // ─── Goal types (reading.goal_type) ──────────────────────
  count: '개수 (count)',
  minimum_cost: '최소 비용',
  maximum_sum: '최대 합',
  maximum_value: '최대 값',
  minimum_value: '최소 값',
  indices: '인덱스 반환',
  boolean_existence: '존재 여부 (true/false)',
  all_combinations: '모든 조합',
  value: '값 계산',
  shortest_path: '최단 경로',
  longest_path: '최장 경로',
  string_output: '문자열 출력',
  sequence: '수열/순서',
  construction: '구성/만들기',

  // ─── Input types (reading.input_summary) ─────────────────
  interval_pairs: '구간 쌍 (시작, 끝)',
  sorted_data: '정렬된 데이터',
  graph_like_relation: '그래프 형태 관계',
  single_array: '1차원 배열',
  '1d_array': '1차원 배열',
  '2d_array': '2차원 배열',
  can_overlap: '겹침 가능',
  string_expression: '문자열 수식',
  only_plus_minus_operators: '+, - 연산자만',
  parentheses_can_be_added: '괄호 추가 가능',
  contains_negative_numbers: '음수 포함',
  contains_zero: '0 포함',
  can_pair_multiply: '쌍으로 묶어 곱하기 가능',
  merge_pairwise: '둘씩 병합',
  cost_depends_on_merge_order: '합치는 순서에 따라 비용 변동',
  coin_denominations: '동전 종류',
  coins_are_multiples_of_previous: '동전이 배수 관계',
  target_value_given: '목표 값 주어짐',
  sorted_ascending: '오름차순 정렬',
  tree_structure: '트리 구조',
  weighted_edges: '가중치 간선',
  unweighted_edges: '비가중치 간선',
  directed_graph: '방향 그래프',
  undirected_graph: '무방향 그래프',
  adjacency_list: '인접 리스트',
  matrix_input: '행렬 입력',
  pair_array: '쌍 배열',
  string_input: '문자열 입력',
  integer_sequence: '정수 수열',
  coordinate_pairs: '좌표 쌍',

  // ─── One-line summaries (reading.one_line_summary) ───────
  max_non_overlapping_intervals: '겹치지 않는 구간 최대 선택',
  activity_selection_problem: '활동 선택 문제',
  maximum_meetings_without_conflict: '충돌 없는 최대 회의 수',
  minimize_expression_by_adding_parentheses: '괄호 추가로 식 최소화',
  group_additions_after_minus_to_minimize: '마이너스 뒤 덧셈 묶어 최소화',
  maximize_sum_by_pairing_and_multiplying: '쌍 묶어 곱해서 합 최대화',
  optimal_number_bundling_for_max_sum: '최적 수 묶기로 최대 합',
  minimize_total_merge_cost: '총 병합 비용 최소화',
  optimal_merge_order_huffman: '최적 병합 순서 (허프만)',
  minimum_coins_for_target_with_multiples: '배수 동전으로 최소 개수',
  greedy_coin_change_with_divisibility: '배수 관계 그리디 동전',

  // ─── Primary patterns (pattern_analysis) ─────────────────
  brute_force: '완전 탐색 (Brute Force)',
  greedy_interval: '그리디 — 구간 선택',
  greedy_grouping: '그리디 — 그룹 묶기',
  greedy_classification: '그리디 — 분류 후 처리',
  greedy_min_heap: '그리디 — 최소 힙',
  greedy_largest_first: '그리디 — 큰 것부터',
  dp_interval: 'DP — 구간',
  dp: '동적 프로그래밍 (DP)',
  dp_backward: 'DP — 역방향',
  dp_forward: 'DP — 정방향',
  dp_coin_change: 'DP — 동전 교환',
  dp_knapsack: 'DP — 배낭',
  dp_lis: 'DP — 최장 증가 부분수열',
  dp_bitmask: 'DP — 비트마스크',
  dp_digit: 'DP — 자릿수',
  dp_tree: 'DP — 트리',
  dp_2d: 'DP — 2차원',
  two_pointers: '투 포인터',
  binary_search: '이분 탐색',
  parametric_search: '매개변수 탐색',
  dfs: '깊이 우선 탐색 (DFS)',
  bfs: '너비 우선 탐색 (BFS)',
  dfs_backtracking: 'DFS + 백트래킹',
  stack_based: '스택 기반',
  sorting_only: '정렬',
  divide_and_conquer: '분할 정복',
  union_find: '유니온 파인드',
  dijkstra: '다익스트라',
  bellman_ford: '벨만-포드',
  floyd_warshall: '플로이드-워셜',
  kruskal: '크루스칼 (MST)',
  topological_sort: '위상 정렬',
  segment_tree: '세그먼트 트리',
  trie: '트라이',
  math_formula: '수학 공식',

  // ─── Reason tags ─────────────────────────────────────────
  need_maximize_count: '개수 최대화 필요',
  locally_optimal_gives_global_optimal: '국소 최적 → 전역 최적',
  overlapping_subproblems: '겹치는 부분 문제',
  optimal_substructure: '최적 부분 구조',
  need_shortest_path: '최단 경로 필요',
  need_connected_components: '연결 요소 필요',
  need_ordering: '순서 필요',
  first_minus_makes_all_after_subtractable: '첫 마이너스 이후 모두 빼기 가능',
  grouping_plus_after_minus_is_always_optimal: '마이너스 뒤 덧셈 묶기가 항상 최적',
  need_dp_for_optimal_substructure: '최적 부분 구조에 DP 필요',
  need_stack_for_nested_structure: '중첩 구조에 스택 필요',
  classify_positive_negative_zero: '양수/음수/0 분류',
  locally_optimal_pairing: '국소 최적 쌍 매칭',
  smallest_first_minimizes_repeated_addition: '작은 것 먼저 합치면 반복 비용 최소',
  merged_result_reenters_candidates: '합친 결과가 후보에 재진입',
  coins_divisibility_guarantees_greedy: '동전 배수 관계가 그리디 보장',
  largest_coin_always_optimal: '큰 동전부터 항상 최적',
  need_dp_for_general_coins: '일반 동전은 DP 필요',
  need_optimal_substructure: '최적 부분 구조 필요',

  // ─── Secondary patterns ──────────────────────────────────
  sorting_preprocessing: '정렬 전처리',
  single_pass: '한 번 순회',
  counting: '카운팅',
  dp_optimization: 'DP 최적화',
  graph_traversal: '그래프 탐색',
  string_split: '문자열 분리',
  accumulation: '누적',
  priority_queue_usage: '우선순위 큐 사용',
  huffman_like: '허프만 코딩 유사',
  division_and_modulo: '나눗셈과 나머지',
  reverse_iteration: '역순 순회',
  prefix_sum: '누적합',
  sliding_window: '슬라이딩 윈도우',
  binary_search_optimization: '이분 탐색 최적화',
  memoization: '메모이제이션',
  backtracking: '백트래킹',

  // ─── Data structures ────────────────────────────────────
  array: '배열',
  set: '집합 (Set)',
  map: '맵 (Map / HashMap)',
  stack: '스택',
  queue: '큐',
  priority_queue: '우선순위 큐 (힙)',
  dp_array: 'DP 배열',
  dp_table: 'DP 테이블',
  linked_list: '연결 리스트',
  deque: '덱 (Deque)',
  tree: '트리',
  graph: '그래프',
  hash_set: '해시 집합',
  hash_map: '해시맵',
  disjoint_set: '서로소 집합',

  // ─── Approach tags (strategy_design) ─────────────────────
  sort_by_end_time: '끝나는 시간 기준 정렬',
  sort_by_start_time: '시작 시간 기준 정렬',
  sort_by_duration: '길이 기준 정렬',
  iterate_and_select: '순회하며 선택',
  track_last_end_time: '마지막 끝 시간 추적',
  dp_with_binary_search: 'DP + 이분 탐색',
  split_by_minus: '마이너스 기준 분리',
  sum_each_group: '각 그룹 합산',
  add_first_group_subtract_rest: '첫 그룹 더하고 나머지 빼기',
  try_all_parentheses: '모든 괄호 조합 시도',
  stack_based_evaluation: '스택 기반 계산',
  separate_positive_negative_zero: '양수/음수/0 분리',
  sort_positive_desc_negative_asc: '양수 내림차순, 음수 오름차순',
  pair_largest_positives: '큰 양수끼리 묶기',
  pair_smallest_negatives: '작은 음수끼리 묶기',
  one_should_not_be_multiplied: '1은 곱하지 않기',
  zero_cancels_leftover_negative: '0으로 남은 음수 상쇄',
  insert_all_to_min_heap: '전부 최소 힙에 삽입',
  extract_two_smallest: '가장 작은 두 개 추출',
  merge_and_reinsert: '합쳐서 다시 삽입',
  accumulate_cost: '비용 누적',
  sort_and_merge_sequentially: '정렬 후 순서대로 합치기',
  iterate_coins_largest_first: '큰 동전부터 순회',
  use_division_for_count: '나눗셈으로 개수 계산',
  update_remainder_with_modulo: '나머지로 갱신',
  dp_bottom_up: 'DP 바텀업',
  dp_top_down: 'DP 탑다운',
  try_all_combinations: '모든 조합 시도',

  // ─── Sorting rules ──────────────────────────────────────
  no_sorting_needed: '정렬 불필요',

  // ─── Edge cases ──────────────────────────────────────────
  same_end_time_sort_by_start: '끝 시간 같으면 시작 시간으로 정렬',
  start_equals_end_zero_length: '시작=끝 (길이 0 회의)',
  start_equals_prev_end_allowed: '시작=이전 끝 허용',
  integer_overflow_large_time: '정수 오버플로우 (큰 시간)',
  empty_input: '빈 입력',
  single_meeting: '회의 1개',
  all_meetings_overlap: '모든 회의 겹침',
  no_minus_in_expression: '식에 마이너스 없음',
  leading_zeros_in_numbers: '숫자 앞의 0',
  only_one_number: '숫자 1개',
  minus_at_start: '시작이 마이너스',
  all_numbers_zero: '모든 숫자 0',
  consecutive_operators: '연속 연산자',
  one_should_add_not_multiply: '1은 곱하지 말고 더하기',
  odd_negatives_use_zero: '홀수 음수 → 0으로 상쇄',
  no_zero_odd_negatives_just_add: '0 없고 음수 홀수 → 그냥 더하기',
  single_element_no_pair: '원소 1개 (짝 없음)',
  all_zeros: '모두 0',
  overflow_possible: '오버플로우 가능',
  all_ones: '모두 1',
  single_bundle_no_merge: '묶음 1개 (합칠 필요 없음)',
  merged_result_must_reenter_heap: '합친 결과를 힙에 재삽입',
  total_cost_overflow_use_long: '총 비용 오버플로우 → long 사용',
  all_same_size_bundles: '모든 묶음 크기 동일',
  two_bundles_only: '묶음 2개만',
  greedy_only_valid_with_multiples: '그리디는 배수 관계일 때만 유효',
  coin_larger_than_K_skip: '동전 > K면 건너뛰기',
  K_equals_zero: 'K = 0',
  single_coin_type: '동전 종류 1개',
  general_coins_need_dp: '일반 동전은 DP 필요',
  negative_cycle: '음수 사이클',
  disconnected_graph: '비연결 그래프',
  self_loop: '자기 루프',
  duplicate_edges: '중복 간선',
  single_node: '노드 1개',

  // ─── Complexity ──────────────────────────────────────────
  'O(1)': 'O(1) — 상수',
  'O(N)': 'O(N) — 선형',
  'O(NlogN)': 'O(N log N)',
  'O(N^2)': 'O(N²)',
  'O(N^3)': 'O(N³)',
  'O(2^N)': 'O(2ᴺ) — 지수',
  'O(N!)': 'O(N!) — 팩토리얼',
  'O(K)': 'O(K)',
  'O(N*K)': 'O(N×K)',
  'O(logN)': 'O(log N)',
  'O(VlogV)': 'O(V log V)',
  'O(V+E)': 'O(V + E)',
  'O(ElogV)': 'O(E log V)',

  // ─── Complexity reasons ──────────────────────────────────
  sorting_dominates: '정렬이 지배',
  single_pass_after_sort: '정렬 후 한 번 순회',
  only_track_last_end_variable: '마지막 끝 시간 변수만 추적',
  store_all_intervals: '모든 구간 저장',
  recursive_calls: '재귀 호출',
  single_pass_parsing: '한 번 파싱',
  split_creates_token_array: '분리 시 토큰 배열 생성',
  no_nested_loops: '중첩 루프 없음',
  store_all_elements: '모든 원소 저장',
  separate_lists_stored: '분류별 리스트 저장',
  constant_extra_space: '상수 추가 공간',
  heap_operations_logN_each: '힙 연산 각각 O(log N)',
  N_minus_1_merges: 'N-1번 병합',
  heap_stores_N_elements: '힙에 N개 저장',
  single_pass_through_coins: '동전 한 번 순회',
  only_count_and_remainder_variables: 'count와 remainder 변수만',
  no_extra_storage_needed: '추가 저장 불필요',
  dp_table_size_K: 'DP 테이블 크기 K',
  dp_array_size_N: 'DP 배열 크기 N',

  // ─── Goal types (추가) ─────────────────────────────────────
  minimum_steps: '최소 단계 수',
  minimum_count: '최소 개수',
  minimum_operations: '최소 연산 횟수',
  count_of_ways: '경우의 수',
  single_value: '단일 값',
  single_integer: '정수 1개',
  single_string: '문자열 1개',

  // ─── Input types (추가) ────────────────────────────────────
  integer_array: '정수 배열',
  single_integer_N: '정수 N 1개',
  two_integers_N_K: '정수 N, K 2개',
  two_strings: '문자열 2개',
  integer_array_with_negatives: '음수 포함 정수 배열',
  directed_weighted_graph: '방향 가중치 그래프',
  single_target_value: '단일 목표 값',
  negative_numbers_in_array: '배열에 음수 포함',
  single_element_array: '원소 1개 배열',

  // ─── Pattern / Algorithm ───────────────────────────────────
  greedy: '그리디',
  sorting: '정렬',
  heap: '힙',
  dynamic_programming: '동적 프로그래밍',
  simulation: '시뮬레이션',
  recursion: '재귀',
  two_pointer: '투 포인터',
  inclusion_exclusion: '포함-배제 원리',
  sweep_line: '스위핑 (Sweep Line)',
  monotone_stack: '단조 스택',
  patience_sorting: '인내 정렬 (Patience Sort)',
  matrix_exponentiation: '행렬 거듭제곱',
  sqrt_decomposition: '제곱근 분할',
  counting_sort: '카운팅 정렬',
  binary_indexed_tree: '펜윅 트리 (BIT)',
  sparse_table: '희소 테이블',
  balanced_bst: '균형 이진 탐색 트리',
  relaxation: '완화 (Relaxation)',
  kruskal_mst: '크루스칼 MST',
  sieve_of_eratosthenes: '에라토스테네스의 체',
  path_compression: '경로 압축',
  union_by_rank: '랭크 기반 합치기',
  bfs_shortest_path: 'BFS 최단 경로',
  dfs_traversal: 'DFS 탐색',
  bfs_dfs: 'BFS/DFS',
  single_source_shortest_path: '단일 출발지 최단 경로',

  // ─── Data structures (추가) ────────────────────────────────
  sorted_array: '정렬된 배열',
  visited_array: '방문 배열',
  dist_array: '거리 배열',
  distance_array: '거리 배열',
  prefix_sum_array: '누적합 배열',
  in_degree_array: '진입차수 배열',
  parent_array: '부모 배열',
  result_array: '결과 배열',
  factorial_array: '팩토리얼 배열',
  color_array: '색상 배열',
  segment_tree_array: '세그먼트 트리 배열',
  list_of_primes: '소수 목록',
  visited_2d_array: '2차원 방문 배열',
  distance_2d_array: '2차원 거리 배열',
  dist_2d_array: '2차원 거리 배열',
  distance_matrix: '거리 행렬',
  dist_matrix_N2: '거리 행렬 N²',
  rolling_array: '롤링 배열',
  recursion_stack: '재귀 스택',
  min_heap: '최소 힙',
  edge_list: '간선 리스트',
  query_results: '쿼리 결과',
  counter_variable: '카운터 변수',
  sorted_list: '정렬된 리스트',
  sorted_string: '정렬된 문자열',
  string_builder: '문자열 빌더',
  adjacency_matrix: '인접 행렬',

  // ─── Reason tags (추가) ────────────────────────────────────
  locally_optimal_not_guaranteed: '국소 최적이 전역 최적 보장 안 됨',
  optimal_substructure_from_smaller_values: '작은 값에서의 최적 부분 구조',
  optimal_substructure_from_prefixes: '접두사에서의 최적 부분 구조',
  greedy_divide_is_not_optimal: '그리디 나눗셈이 최적 아님',
  need_all_primes_in_range: '범위 내 모든 소수 필요',
  fibonacci_structure: '피보나치 구조',
  digit_level_constraint: '자릿수 단위 제약',
  counting_with_constraints: '조건부 카운팅',
  adjacent_relation_matters: '인접 관계 중요',
  constant_work_per_cell: '셀당 상수 작업',
  constant_work_per_step: '단계당 상수 작업',
  constant_operations_per_step: '단계당 상수 연산',
  constant_transitions_per_state: '상태당 상수 전이',
  constant_variables_only: '상수 변수만',
  amortized_O1_per_element: '원소당 분할상환 O(1)',
  each_element_pushed_popped_once: '각 원소 push/pop 1회씩',
  each_node_and_edge_processed_once: '노드·간선 각 1회 처리',
  bfs_visits_each_node_edge_once: 'BFS 노드·간선 1회 방문',
  heap_operations_logN: '힙 연산 O(log N)',
  union_find_nearly_constant_per_op: '유니온 파인드 연산당 거의 O(1)',
  segment_tree_is_O_NlogN: '세그먼트 트리 O(N log N)',
  triple_loop_N3: '3중 루프 O(N³)',
  simulation_is_O_N2: '시뮬레이션 O(N²)',
  N_too_large_for_O_N2: 'N이 O(N²)에 너무 큼',

  // ─── Approach tags (추가) ──────────────────────────────────
  sort_and_two_pointer: '정렬 + 투 포인터',
  sort_edges_by_weight: '가중치 기준 간선 정렬',
  built_in_sort: '내장 정렬',
  dp_bottom_up_1_to_N: 'DP 바텀업 1→N',
  dp_2d_state: 'DP 2차원 상태',
  dp_base_case_dp1_eq_0: 'DP 기저: dp[1]=0',
  bottom_up_from_1_to_N: '바텀업 1부터 N까지',
  must_compare_all_three_operations: '세 연산 모두 비교 필요',
  check_divisibility_before_access: '나눗셈 가능 여부 먼저 확인',
  try_all_split_points: '모든 분할 지점 시도',
  dp_table_N_by_N: 'DP 테이블 N×N',
  pascal_triangle_dp: '파스칼 삼각형 DP',
  visit_each_cell_once: '각 셀 1회 방문',
  visit_each_node_and_edge_once: '각 노드·간선 1회 방문',
  iterate_all_components: '모든 컴포넌트 순회',
  compute_in_degrees: '진입차수 계산',
  dfs_post_order_reverse: 'DFS 후위순회 역순',
  extract_min_from_heap: '힙에서 최솟값 추출',
  union_find_cycle_detection: '유니온 파인드 사이클 감지',
  single_pass_through_array: '배열 한 번 순회',
  single_pass_through_string: '문자열 한 번 순회',
  single_pass_1_to_N: '1→N 한 번 순회',
  edge_sorting: '간선 정렬',
  squared_distance_comparison: '제곱 거리 비교',
  avoid_floating_point: '부동소수점 회피',
  cross_product_sign: '외적 부호',
  backtracking_reconstruction: '백트래킹 복원',

  // ─── Edge cases (추가) ─────────────────────────────────────
  negative_numbers: '음수',
  duplicate_values: '중복 값',
  all_same_values: '모든 값 동일',
  all_same_characters: '모든 문자 동일',
  all_same_values_answer_is_1: '모든 값 동일 → 답 1',
  N_equals_1_answer_is_1: 'N=1이면 답 1',
  N_equals_1_answer_is_0: 'N=1이면 답 0',
  N_equals_1_trivial: 'N=1 자명한 경우',
  N_equals_2_trivial: 'N=2 자명한 경우',
  N_equals_2_or_3: 'N=2 또는 3',
  n_equals_1_answer_is_1: 'N=1이면 답 1',
  K_equals_0_answer_is_1: 'K=0이면 답 1',
  K_equals_1: 'K=1',
  single_element_range: '원소 1개 범위',
  self_loop_possible: '자기 루프 가능',
  bidirectional_edges: '양방향 간선',
  multiple_edges_between_same_pair: '같은 쌍에 다중 간선',
  negative_edges_present: '음수 간선 존재',
  disconnected_components: '비연결 컴포넌트',
  disconnected_graph_check_all_components: '비연결 그래프 → 모든 컴포넌트 확인',
  single_node_is_bipartite: '노드 1개는 이분 그래프',
  cycle_detection_needed: '사이클 감지 필요',
  order_must_be_preserved: '순서 보존 필요',
  ascending_order_output: '오름차순 출력',
  boolean_reachability: '도달 가능 여부 (boolean)',
  boolean_per_query: '쿼리당 boolean',
  skip_outdated_entries: '만료된 항목 건너뛰기',
  overflow_prevention: '오버플로우 방지',
  no_leading_zero_dp1_0_equals_0: '선행 0 불가 → dp[1][0]=0',
  mod_at_every_step: '매 단계 mod 연산',
  mod_at_every_addition: '매 덧셈 mod 연산',
  modular_output_required: 'mod 출력 필요',
  large_N_up_to_1M: 'N 최대 100만',

  // ─── IO / 성능 ────────────────────────────────────────────
  fast_io: '빠른 입출력',
  fast_io_critical: '빠른 입출력 필수',
  fast_io_mandatory: '빠른 입출력 필수',
  fast_io_for_large_M: '큰 M에 빠른 입출력 필요',

  // ─── 공간 복잡도 이유 ──────────────────────────────────────
  no_auxiliary_structure: '보조 자료구조 없음',
  no_extra_structure: '추가 구조 없음',
  no_extra_array_needed: '추가 배열 불필요',
  no_auxiliary_data_structure: '보조 자료구조 없음',
  only_two_variables_maintained: '변수 2개만 유지',
  only_constant_variables: '상수 변수만',
  two_variables: '변수 2개',
  integer_variables: '정수 변수',
  input_array_stored: '입력 배열 저장',
  space_optimization: '공간 최적화',
  space_optimization_1d: '1차원 공간 최적화',
  static_array_no_updates: '정적 배열 (갱신 없음)',
  tree_array_size_4N: '트리 배열 크기 4N',
  dp_array_size_N_plus_1: 'DP 배열 크기 N+1',
  bfs_alternative: 'BFS 대안',
  hash_set_alternative: '해시 집합 대안',
  union_find_alternative: '유니온 파인드 대안',
  data_structure_design: '자료구조 설계',
  traversal_order: '탐색 순서',

  // ─── 그래프 (추가) ────────────────────────────────────────
  queue_for_bfs: 'BFS용 큐',
  bfs_per_node: '노드당 BFS',
  bfs_from_each_node: '각 노드에서 BFS',
  in_degree_tracking: '진입차수 추적',
  init_dist_INF_start_zero: '거리 INF 초기화, 시작점 0',
  dist_array_size_V: '거리 배열 크기 V',
  dist_array_size_N: '거리 배열 크기 N',
  adjacency_list_size_M: '인접 리스트 크기 M',
  adjacency_list_size_N_plus_M: '인접 리스트 크기 N+M',
  read_adjacency_matrix: '인접 행렬 읽기',

  // ─── 기타 (추가) ──────────────────────────────────────────
  index_tracking: '인덱스 추적',
  formula_simplification: '공식 단순화',
  recursive_definition: '재귀적 정의',
  multiple_operations_available: '여러 연산 사용 가능',
  target_is_fixed_value_1: '목표가 고정값 1',
  range_sum_queries: '구간 합 쿼리',
  prefix_sum_update_is_O_N: '누적합 갱신 O(N)',
  many_queries_need_fast_response: '많은 쿼리 → 빠른 응답 필요',
  each_query_O_1: '쿼리당 O(1)',
  graph_structure: '그래프 구조',
  tree_depth: '트리 깊이',
  floating_point_arithmetic: '부동소수점 연산',
  k_loop_outermost: 'K 루프가 최외곽',
  all_pairs_shortest_path_needed: '모든 쌍 최단 경로 필요',
};

// ─── Constraint keys ───────────────────────────────────────
const CONSTRAINT_LABELS: Record<string, string> = {
  input_size_hint: '입력 크기',

  // Greedy
  non_overlapping_required: '겹치지 않아야 함',
  simultaneous_end_start_allowed: '끝=시작 동시 허용',
  expression_length_max: '식 길이 제한',
  operators_plus_minus_only: '+, - 연산자만',
  can_bundle_pairs: '쌍으로 묶기 가능',
  negative_numbers_possible: '음수 가능',
  zero_included: '0 포함',
  must_merge_all: '전부 합쳐야 함',
  merge_cost_is_sum: '합치는 비용 = 합',
  coins_are_multiples: '동전이 배수 관계',
  unlimited_coins: '동전 무제한',

  // DP
  three_operations: '3가지 연산',
  divide_by_3_if_divisible: '3으로 나누어지면 ÷3',
  divide_by_2_if_divisible: '2로 나누어지면 ÷2',
  subtract_1: '-1',
  fibonacci_definition: '피보나치 정의',
  fib_0_is_0: 'F(0) = 0',
  fib_1_is_1: 'F(1) = 1',
  adjacent_digit_diff_is_1: '인접 자릿수 차이 = 1',
  no_leading_zero: '선행 0 불가',
  mod_1000000000: 'mod 10⁹',
  mod_10007: 'mod 10007',
  rectangle_height_is_2: '직사각형 높이 = 2',
  no_consecutive_ones: '연속 1 불가',
  binary_digits_only: '이진수만',
  binary_matrix: '0/1 행렬',
  answer_is_area_not_side: '정답은 넓이 (변 아님)',
  uppercase_only: '대문자만',
  lowercase_only: '소문자만',
  need_actual_lcs_string: '실제 LCS 문자열 필요',
  strictly_increasing: '순증가',
  need_actual_subsequence: '실제 부분수열 출력',
  each_day_has_duration_and_profit: '매일 기간+수익',
  consultation_must_finish_by_day_N: 'N일까지 상담 완료',
  can_remove_at_most_one: '최대 1개 제거 가능',
  must_select_at_least_one: '최소 1개 선택 필수',
  multiplication_is_associative: '곱셈 결합법칙',
  no_same_position_both_feet: '양발 같은 위치 불가',
  movement_costs_vary: '이동 비용 다양',
  visit_all_cities_exactly_once: '모든 도시 정확히 1번 방문',

  // Graph
  truth_propagation: '진실 전파',
  undirected_grouping: '무방향 그룹핑',
  negative_weights_possible: '음수 가중치 가능',
  undirected_graph: '무방향 그래프',
  positive_cycle_to_destination_check: '목적지까지 양의 사이클 확인',
  unreachable_case: '도달 불가 경우',
  reverse_direction: '역방향',
  multiple_answers_possible: '답이 여러 개 가능',
  all_pairs_shortest: '모든 쌍 최단경로',
  small_N: 'N이 작음',
  alphabet_to_number_conversion: '알파벳→숫자 변환',
  disconnected_returns_minus_1: '비연결 시 -1 반환',
  parallel_build_possible: '동시 건설 가능',
  predecessor_max_not_sum: '선행 최대값 (합 아님)',
  multiple_test_cases: '다중 테스트 케이스',
  may_be_disconnected: '비연결일 수 있음',
  path_compression_required: '경로 압축 필요',
  union_by_rank_required: '랭크 기반 합치기 필요',
  positive_weights_only: '양수 가중치만',
  priority_queue_needed: '우선순위 큐 필요',
  k_shortest_paths: 'K번째 최단 경로',
  revisit_allowed: '재방문 허용',
  positive_weights: '양수 가중치',
  single_source_single_dest: '단일 출발-도착',
  critical_path_and_edge_count: '임계 경로 + 간선 수',
  reverse_backtracking_needed: '역방향 추적 필요',
  connectivity_check: '연결성 확인',
  order_irrelevant: '순서 무관',
  state_space_small: '상태 공간 작음',
  six_transitions_per_state: '상태당 6가지 전이',
  any_valid_topological_order: '유효한 위상 순서 아무거나',
  no_cycle_guaranteed: '사이클 없음 보장',
  transitive_closure: '추이적 폐포',
  self_loop_via_cycle: '사이클 통한 자기 루프',
  multiple_edges_same_pair: '같은 쌍에 다중 간선',
  no_path_output_zero: '경로 없으면 0 출력',
  negative_weights: '음수 가중치',
  negative_cycle_detection: '음수 사이클 감지',
  bridge_straight_line_only: '다리는 직선만',
  bridge_length_at_least_2: '다리 길이 ≥ 2',
  unit_weight_edges: '가중치 1 간선',
  exact_distance_K: '정확히 거리 K',

  // Tree
  node_deletion: '노드 삭제',
  subtree_removal: '서브트리 제거',
  binary_tree: '이진 트리',
  root_is_A: '루트 = A',
  root_is_one: '루트 = 1',
  no_update_queries: '갱신 쿼리 없음',
  range_minimum_query: '구간 최솟값 쿼리',
  naive_lca_possible: '단순 LCA 가능',
  binary_lifting_required: '바이너리 리프팅 필요',
  point_update: '점 갱신',
  range_product_query: '구간 곱 쿼리',
  range_sum_query: '구간 합 쿼리',
  modular_arithmetic: '모듈러 연산',
  undirected_tree: '무방향 트리',
  membership_check: '포함 여부 확인',
  large_value_range: '값 범위 큼',

  // Number theory
  range_query: '범위 쿼리',
  sieve_required: '에라토스테네스 체 필요',
  gcd_lcm_required: 'GCD/LCM 필요',
  repunit_numbers: '레퍼닛 수',
  unsigned_64bit: '부호 없는 64비트',
  almost_prime_definition: '거의 소수 정의',
  large_range: '큰 범위',
  prime_and_palindrome: '소수 + 회문',
  sieve_range_larger_than_N: '체 범위 > N',
  euler_totient: '오일러 피 함수',
  large_n: 'N이 큼',
  squarefree_number: '제곱 인수 없는 수',
  range_sieve_required: '범위 체 필요',
  linear_diophantine: '일차 디오판토스 방정식',
  extended_gcd_required: '확장 유클리드 필요',
  tree_structure: '트리 구조',
  fraction_propagation: '분수 전파',

  // Data structures / Search / Sorting / etc.
  sorted_input: '정렬된 입력',
  coordinate_compression: '좌표 압축',
  merge_sort_based: '병합 정렬 기반',
  stable_sort_required: '안정 정렬 필요',
  custom_comparator: '사용자 정의 비교',

  // Combinatorics
  combination_formula: '조합 공식',
  modular_inverse: '모듈러 역원',
  pascal_triangle: '파스칼 삼각형',

  // Geometry
  circle_intersection: '원 교차',
  point_in_circle: '원 안의 점',
  line_segment_intersection: '선분 교차',
  cross_product: '외적',
};

/**
 * 영문 tag를 한글 라벨로 변환
 * 매핑이 없으면 underscore를 공백으로 바꿔서 반환
 */
export function getTagLabel(tag: string): string {
  if (TAG_LABELS[tag]) return TAG_LABELS[tag];
  // fallback: underscore → space, 첫 글자 대문자
  return tag.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}

/**
 * constraint key를 한글 라벨로 변환
 */
export function getConstraintLabel(key: string): string {
  if (CONSTRAINT_LABELS[key]) return CONSTRAINT_LABELS[key];
  return key.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}
